### ISSUE TITLE
Build an initial implementation of the thumbnail navigation strip

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1661]
Future work: use as a companion window w/ those behaviors

 - [x] Navigation by element representing canvas
 - [x] Configurable height
 - [x] Configuration: show by default #1686 
 - [x] Scroll thumbs to current canvas #1687
 - [x] Lazy load thumbnails #1689
 - [x] Create a virtualized long list for memory, performance #1688
 - [ ] Review Carousel accessibility guidelines https://www.w3.org/WAI/tutorials/carousels/ #1690

**Comment by camillevilla** [comment]
Closing this since we're well past an initial implementation. Accessibility review for the carousel guidelines has been rolled into a holistic accessibility review for Sprint 4.
