### ISSUE TITLE
Workspace sidebar menu [overview]

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1726]
**Note:** This is an overview, so it shouldn't be assigned to a single person 🙃
![annotated-workspace-menu](https://user-images.githubusercontent.com/5402927/51932229-948e9080-23b3-11e9-93f9-7c07e9028f6d.png)

- [x] 3 - List all open windows - #1728
- [x] 4 - Settings - added, but no-op. Simple theme toggle added in #1755
- [x] 6 - Simple download / export workspace - #1787 
- [ ] 5 - Share / save workspace 🎟 needs design for importing a workspace UX
- [ ] 1 - Expose all windows 🛑 - waiting for infinite window mode designs
- [ ] 2 - Tile all in frame  🛑 - waiting for infinite or grid window mode designs

**Comment by camillevilla** [comment]
@ggeisler and @jvine

Is this menu from the interactive mockup an ok place to start for item 4? We won't be able to implement the click-and-center behavior until more windowing decisions shake out. But a developer could start out by creating a non-interactive version of this list:
![list of windows](https://user-images.githubusercontent.com/5402927/51932536-3b732c80-23b4-11e9-8df0-e805a8ed4716.png)

**Comment by jvine** [comment]
Yes, I think this makes sense - I was going to suggest it too.

**Comment by camillevilla** [comment]
Closing this issue in favor of other workspace behavior tickets that have been better specified by Gary and Jennifer elsewhere.
