### ISSUE TITLE
Update canvas navigation area with label and zoom controls (story)

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2110]
There are several distinct updates we want to make in the area where the window canvas navigation buttons currently are. Here's an overview of the updates and I'll make separate tickets for each distinct update.

<img width="512" alt="overall" src="https://user-images.githubusercontent.com/101482/54046158-c8b65780-4190-11e9-8567-a7f9e5287a1e.png">

- [x] #2111 - Add a canvas nav/label container that encloses the elements below
- [x] #2112 - Move the canvas zoom controls down so that they are in a row with the current canvas navigation buttons (A in the mockup above)
- [x] #2113 - Display the canvas label below the zoom and nav buttons (B)
- [x] #2114 - Add a page counter next to the canvas labels (C)
- [x] #2160 Only show the canvas nav/label container when the window is focused 
- [x] #2167 responsive separator behavior
- [x] #2212 Truncate the canvas title when necessary

**Comment by aeschylus** [comment]
Does this imply we need to add a margin to the constraint box in OSD? Otherwise it may not be possible to view the area of the image underneath the overlay.

**Comment by ggeisler** [comment]
I'm not sure I know what the "constraint box in OSD" is. We do want to be able to view the area of the image underneath the overlay, so I guess whatever needs to be done to enable that.

Are there some potential drawbacks or problems to doing this?

**Comment by cbeer** [comment]
It seems like the current behavior is fine, no?

**Comment by ggeisler** [comment]
@cbeer Not sure if you are asking me or @aeschylus are what specific behavior you are referring to.

If it is about the way the current zoom controls appear, visually, the problem with them currently is that they can become invisible over darker backgrounds, as can the canvas navigation buttons. So the purpose of the semi-transparent background container is to ensure there is always at least some contrast that enables the navigation area controls and labels to be visible, no matter how light or dark the image is. This is even more important since we're adding the canvas label to the display.

**Comment by cbeer** [comment]
I think we talked about it at sprint planning; I'm not seeing any cases where the overlay makes it impossible to see the image.
