### ISSUE TITLE
Update dialogs (story)

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2286]
The application currently includes several dialogs, all of which need updating. Here are the actual work issues:

- [x] #2287 - Update the "Settings" dialog to be "Change theme"
- [x] #2288 - Update the "Select workspace type" dialog
- [x] #2289 - Update the "Download/Export" dialog
- [x] #2290 - Update the "Import workspace" dialog

## General info on dialogs

The current dialogs should follow one of two component types:

- [Simple dialogs](https://material-ui.com/demos/dialogs/#simple-dialogs)
- [Form dialogs](https://material-ui.com/demos/dialogs/#form-dialogs)

All dialogs should follow these styling guidelines:
- Title of the dialog is left-aligned
- Title uses Headline 2 typography defined in #2093 
- Text buttons use the BUTTON class typography defined in #2093 

### Simple dialogs
[Simple dialogs](https://material-ui.com/demos/dialogs/#simple-dialogs) enable the user to pick from a list of visible options. The selected option takes effect immediately and closes the dialog at the same time.

### Form dialogs
[Form dialogs](https://material-ui.com/demos/dialogs/#form-dialogs) contain action buttons. The user can select an action or cancel to close the dialog.

For all form dialogs:

- Buttons use the secondary color
- Buttons are right-aligned
- The leftmost one is always labeled "CANCEL" and is a [text button](https://material-ui.com/demos/buttons/#text-buttons)
- The rightmost one is the action that the dialog is intended to provide and is a [contained button](https://material-ui.com/demos/buttons/#contained-buttons)
