### ISSUE TITLE
Define default configuration of embedded mode

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2378]
There might not actually be too much to this, since most of the configuration of a given embedded instance is just overriding Mirador's default configuration in the embedding application code (if I understand things correctly). But here are the things that we don't currently have, or we might already have but I want to be sure of, that would be necessary for a good and flexible embedding scenario:

- [x] Suppress window close button

- [ ] https://github.com/ProjectMirador/mirador/issues/2503 Replace the window maximize icon with the workspace maximize icon (because maximizing a single window in mosaic mode doesn't do much, but fullscreening the whole viewer could have real benefit). The workspace maximize icon should have the same behavior as it does in standalone Mirador, where it full-screens the embedded Mirador viewer. So the window top bar in embedded mode would ideally look similar to this:

<img width="547" alt="Screen Shot 2019-04-11 at 10 51 25 AM" src="https://user-images.githubusercontent.com/101482/56002460-55b06d00-5c77-11e9-9abd-1e2144ad451d.png">

- [x] Configure zoom controls to be `on` instead of the default `off` (#2504)

- [x] Configure Workspace app bar to be `off` instead of the default `on`

- [x] Configure the side panel to display be default a panel other than `information` (see #2402)

- [x] Configure the side panel to display be open by default (see #2402)

- [x] Configure the default language

- [ ] Make the viewer switch languages automatically if the containing application is using a locale other than the default language and that language is defined in Mirador's `availableLanguages` configuration (if technically feasible)

**Comment by camillevilla** [comment]
I started a wiki page for this config bundle:
https://github.com/ProjectMirador/mirador/wiki/M3-Configuration-Recipes

**Comment by jkeck** [comment]
For the `Make the viewer switch languages automatically` are we imaging something other than setting the `langauge` when initializing Mirador?

**Comment by mejackreed** [comment]
I was thinking that `Make the viewer switch languages automatically` was really about how an adopter utilizes the existing API's. For instance in our cases, the containing application would control Mirador and set its language appropriately via its config.

Automatic language detection within Mirador caused some problems for implementation scenarios in Mirador 2 in my experience.

**Comment by jkeck** [comment]
Yeah, agreed, automatic language detection is probably a non-starter.  So is that bullet in this ticket just about documenting that appropriately?  Just trying to figure out what the actionable task is for that particular bullet.

**Comment by ggeisler** [comment]
We weren't sure how feasible automatic locale detection might be, so that item was more of a "nice to have if possible" I guess. I updated the item to indicate that, so feel free to consider the task non-actionable.

**Comment by camillevilla** [comment]
Great. I've added a link to the i18n docs in the config recipe. 
https://github.com/ProjectMirador/mirador/wiki/M3-Configuration-Recipes

I believe this ticket is done, aside from the maximize window button work that was split out to #2503. 

@ggeisler, try out this settings bundle and let me know if that meets your criteria. I'll wait for your 👍 before closing this ticket.
https://github.com/ProjectMirador/mirador/wiki/M3-Configuration-Recipes#single-item-view-work-in-progress-see-2378

**Comment by ggeisler** [comment]
@camillevilla Nice, I pulled the `2402-default-sidebar-stateee` branch to get the new sidepanel settings and updated my configuration to use your example config settings and things look 👍

**Comment by ggeisler** [comment]
@camillevilla I had previously replaced the checkbox for the second item with a link to #2503 so we don't need to wait for that ticket to be closed before closing this ticket (since we agreed that the last, language detection item has been deemed not feasible, the second item is the only one keeping this ticket open).

I suggest we close this ticket and just track #2503 on its own.
