### ISSUE TITLE
Update theming (primary/secondary colors and dark mode)

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2518]
Below are just some baby steps in improving the theming. There are still some challenges related to color contrast for accessibility and getting things correctly set up for institutional theming (going beyond just "light' and "dark" themes). But we can iterate after these changes get in.

### Update the theme settings for primary and secondary colors
- [x] Redefine the current `secondary.main` color (`#1967d2`) to be the `primary.main` color
- [x] Define a new color (`#ffa224`) to `secondary.main`
- [x] Update all `secondary.main` color assignments to use `primary.main` (so the end result no visible change to the UI; the FAB, current window top border, controls, etc. are still blue)
- [x] Assign the new `secondary.main` color to the notification dot currently used to indicate a canvas has annotations. So the dot will change from red to orange.

After the changes above are made, things should look similar to this:

<img width="539" alt="Screen Shot 2019-04-15 at 3 32 45 PM" src="https://user-images.githubusercontent.com/101482/56169696-d29f5780-5f93-11e9-8fa5-354ce04a7866.png">

### Give dark mode a different primary color
- [x] Define a different primary color in dark mode: `#4db6ac`

After making the changes above, when you change to the dark theme, the FAB, side panel icon menu highlight, and form controls should change to a teal color:

<img width="539" alt="Screen Shot 2019-04-15 at 3 38 30 PM" src="https://user-images.githubusercontent.com/101482/56169899-8acd0000-5f94-11e9-96d5-c99593990a7e.png">

### Update component assignments to work better in dark mode
- [x] Update the companion window panel header background so that is remains the current color in light mode, but changes to be `grey[700]` (`#616161`) in dark mode.
- [x] Update the workspace background so that is remains the current color in light mode, but changes to be `grey[700]` (`#616161`) in dark mode.

After those changes, in dark mode the workspace background and window panel header background should look like this:

<img width="539" alt="Screen Shot 2019-04-15 at 3 37 49 PM" src="https://user-images.githubusercontent.com/101482/56169878-72f57c00-5f94-11e9-84b4-6ef9a538a656.png">
