### ISSUE TITLE
Add layers panel to window (story)

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2607]
This is a story ticket that provides some general background. The specific relevant work tickets are:

- [x] #2608 Add layers menu icon
- [x] #2609 Enable drag and drop of layers
- [x] #2610 Add layer thumbnail and label
- [x] #2611 Enable toggling layer visibility
- [x] #2612 Add move-to-top action for layers
- [x] #2613 Add layer opacity controls
- [x] #2614 Add layer section divider

### Background
Layers is an existing feature of Mirador 2. The layer features we suggest should be core in Mirador 3 are very similar, but for Mirador 3 there are a couple of significant updates:

- The list of layers is stacked, as with layers in an application like Photoshop, such that from a z-index perspective the layer at the top of the list in the layer panel has the highest z-index value. The last layer in the list has the lowest z-index value of all layers in the list. This means that, unlike in Mirador 2, if all layers are visible and at 100% opacity, you will only see the image in the topmost layer.

- To give users necessary flexibility for image analysis, layers should be moveable, so the relative z-index of a given layer can effectively be changed by the user.

Of the existing panel types, the layers panel is most similar to the annotations panel. Just as each annotation gets its own divided section in the annotations panel, each layer of an object gets its own divided layer section. For example, here's an object with three layers:

![layers-panel](https://user-images.githubusercontent.com/101482/57406983-f589e980-7196-11e9-94af-e9f5d028c481.png)

---

The work tickets linked above include adding the layers panel and the following layers features:

- List all layers by thumbnail and label
- Toggle visibility of layer
- Adjust layer opacity
- Reorder layers
- Move layer to top

Here's an [interactive mockup](https://xd.adobe.com/view/c0b13056-4bea-4164-78a6-c716d635089a-b680/) of those features.

### Potentially useful sample manifests with layers defined
Note that at the time of writing this ticket, only the first of the manifests below loads images in Mirador 3; all but the last work, including displaying layers, in Mirador 2.

- [Reconstructed manifest (partial): Grandes Chroniques de France](https://demos.biblissima.fr/iiif/metadata/BVMM/chateauroux/manifest.json)(Multiple canvases, each with two layers)
- [Letter from Alexander Hamilton Papers](https://prtd.app/hamilton/manifest.json) (One canvas with many multi-spectral layers)
- [Ars memorandi per figuras Evangelistarum](https://prtd.app/aom/manifest.json) (Several canvases, each with many multi-spectral layers)
- [Flute Vault](https://prtd.app/fv/manifest.json) (One canvas, two layers)
- [Osborn fa1 IIIF Manifest created for the Digitally Enabled Scholarship with Medieval Manuscripts project at Yale University](https://manifests.britishart.yale.edu/Osbornfa1) (Multiple canvases, one of which has many layers, but doesn't currently load in either Mirador 2 or Mirador 3)
