### ISSUE TITLE
Update authentication-related UI elements

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2636]
The intention (based on discussion with @cbeer and @jvine) is to switch the authentication UI elements [currently a snackbar and a modal dialog](https://github.com/ProjectMirador/mirador/pull/2367) to a single, expandable div that is displayed at the top of the object window, just below the window top bar (example on left below).

This `div` does not overlay the window canvas but is inserted between the window top bar and the canvas/side panel/companion window content. This means when the user clicks "Continue", the `div` expands and pushes the canvas/sidebar panel/companion windows down (example on right below).

<img width="1491" alt="expandable-div" src="https://user-images.githubusercontent.com/101482/58719499-ae9da700-8384-11e9-9318-784b2105979d.png">

Here are same examples but in a scenario where the user has the window side panel open:

<img width="1491" alt="expandable-div-sidepanel" src="https://user-images.githubusercontent.com/101482/58719569-e1479f80-8384-11e9-871b-dd650f04d35f.png">

The same `div` should be used to show the failure message when necessary:

<img width="728" alt="general-failure" src="https://user-images.githubusercontent.com/101482/58719618-020ff500-8385-11e9-8b30-7f2d8c38d8f8.png">

### Initial collapsed state
Details of the initial, collapsed `div` (or a variation of a companion window; whatever makes sense technically):

<img width="401" alt="collapsed-details" src="https://user-images.githubusercontent.com/101482/58720363-ce35cf00-8386-11e9-9b5f-f8295108e782.png">

- [x] `div` is full width of the window, inserted directly after the window top bar. Background color is the current palette's secondary color. (Presumably the `onText` color is calculated automatically based on the background color? If not, we might have to discuss expanding the theme configuration to give the auth div explicit background and text colors.)
- [x] Lock icon: `lock` icon (@material-ui/icons/LockSharp). Ensure it has something like `margin-right: 12px` to separate it from the label text.
- [x] Value of the 'label' property is the text next to the lock icon.
- [x] Make 'label' an `h3` but style it using the `body1` [typography](https://github.com/ProjectMirador/mirador/issues/2093).
- [x] The text "CONTINUE", in `body1` typography, with something like `margin-left: 20px` to offset it from the `label` text.
- [x] Although the "CONTINUE" text looks like a text button, we'd rather make the whole _lock icon/label text/CONTINUE_ block a single button, which when selected would toggle the `div` open (showing the full auth message and action buttons) and closed (the initial state).

### Expanded state
When the user toggles the auth `div` open, it expands to show the "recommended" elements `header` and `description` and the action buttons:

<img width="686" alt="expanded-details" src="https://user-images.githubusercontent.com/101482/58720586-73e93e00-8387-11e9-9d79-a5674e301e12.png">

- [x] If provided, display the 'header' value, styled using `body1` typography.
- [x] If provided, display the 'description' value.
- [x] If both header' and 'description' are provided, insert a colon after `value` so it reads as in the mockup above.
- [x] Add a text button labelled "Cancel", as in the mockup.
- [x] When selected, the "Cancel" button should collapse the `div` back to its initial state.
- [x] Add a primary action button next to the "Cancel" button, using the filled button style. If provided, use the `confirmLabel` value as the button label. If `confirmLabel` is not provided, use the fallback text in  #2637 and #2638 for the button label.
- [x] When selected, the primary action button should trigger the opening of the authentication service, as it does in the current implementation.
- [x] The "CONTINUE" text should be hidden when the `div` is in the expanded state (forgot to remove it from the mockup).

### Failure state
If the user succeeds in authenticating (or agrees to the terms of service), the auth `div` should be removed. If the user's authentication/terms of service action results in failure, however, we need to show a failure message(s):

<img width="686" alt="failure-details" src="https://user-images.githubusercontent.com/101482/58720947-6bddce00-8388-11e9-87aa-9d438d50f9de.png">

- [x] Maintain the lock icon and the action buttons from the expanded state of the `div`, but replace the text as described next:
- [x] If provided, show the 'failureHeader' value next to the lock icon. If not provided, use the fallback text in #2637, #2638, and #2639 instead.
- [x] If provided, show the 'failureDescription' value below. If not provided, omit the description.
- [x] If the user selects the "Cancel" button in the failure state, the `div` should return to the initial state (collapsed, showing the label as described in the "Initial collapsed state" section above).
- [x] The "Login" button should trigger opening the authentication service, same as when in the expanded state.

### Example manifest
Mockups above based on:
- Manifest: https://iiifauth.digtest.co.uk/manifest/11_kitty_joyner
- Auth section: https://iiifauth.digtest.co.uk/img/11_kitty_joyner_degraded.jpg/info.json

### Fallback text
Since only one of the six auth text properties is **required**, we should in some cases provide fallback text when a given property doesn't have a value. The fallback text depends on context (which authentication pattern is in play), so I'm creating separate tickets with the details for each auth pattern:

#2637 - Customize auth details for Login pattern
#2638 - Customize auth details for Clickthrough pattern
#2639 - Customize auth details for Kiosk and External patterns

### Theme examples
If we base the background color of the auth `div` on the secondary color of the theme as suggested earlier, the mockups above are what we'd get from the current Mirador 3 default light theme. Here's how it would look when switching to the default dark theme:

<img width="1499" alt="dark-theme" src="https://user-images.githubusercontent.com/101482/58721321-895f6780-8389-11e9-9982-435b86ae6913.png">

And a custom theme:

<img width="1504" alt="sul-theme" src="https://user-images.githubusercontent.com/101482/58721383-bca1f680-8389-11e9-9654-22b29ffe72bd.png">
