### ISSUE TITLE
Add full detail view of truncated search result item

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2688]
If a search result is [truncated due to length](#2671), the user should be able to select the "more ..." link and see the Search panel body updated to show a full rendering of that search result:

<img width="330" alt="Screen Shot 2019-06-12 at 10 39 57 AM" src="https://user-images.githubusercontent.com/101482/59373602-d97de880-8cfe-11e9-838e-ba4dd0794b61.png">

- [ ] Provide a "Back to results" link, using `Subtitle 2` [typography](https://github.com/ProjectMirador/mirador/issues/2093).

- [x] Make the `arrowBackSharp` icon part of the "Back to results" link.

- [x] Show the hit counter and canvas label of the search result item, using the same typography as described in notes B and C of #2683. I believe the hit counter will always be the version with the yellow background since if the user selects an item's "more ..." link we would make that the currently selected item if it wasn't already.

- [x] If the result item has a label, include it in the same way as described at the bottom of the #2683 ticket description.

- [x] Display the full content of the search result item.

- [x] The search panel header elements (search box, clear button, page and hit result navigation) should be the same as they were before navigating to the detail panel.

- [x] If the user uses the hit result navigation buttons to move forward or backward through the search result list, the user should **stay** on the detail panel and see the full display of the result item navigated to. In other words, the user should be able to navigate the results one-by-one in the full detail view.

- [x] If search result _page_ navigation is present in the search panel header, the point above applies there as well. For example, if the user is on the full detail view of result item `#3`, which is on page 1 of 5 pages where each page contains 5 results, if the user chooses to navigate to the last page from the detail panel, they should see the panel body display the full detail view of result item `#21` (with all the other relevant elements -- canvas, hit counter navigation -- changing in coordination).
