### ISSUE TITLE
Allow a mirador window to be initialized with a content search query

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#2754]
This is in order to support the scenarios laid out in:
- [x] sul-dlss/sul-embed#1019
- [x] sul-dlss/sul-embed#1022
- [ ] sul-dlss/sul-embed#1023
