### ISSUE TITLE
Refactor manifest fetching (roadmap)

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3049]
- [ ] separate the HTTP mechanics and tracking from the workspace catalog list (#3048)
- [ ] add a workspace-level component to load manifests in the background (perhaps with some developer friendly debugging features and/or a user-facing loading indicator)
- [ ] consolidate the lazy-loading `fetchManifest` logic into that component (not so bad right now, but gets ugly fast when introducing collections)
- [ ] add some garbage collection to clean up unused manifest data from state to avoid too much bloating(?)
- [ ] eager-load some additional manifest data (e.g., manifest `partOf` data)
- [ ] ???
