### ISSUE TITLE
Specification support tracker issue

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#630]
Specification related bugs:
- [x] Canvas/Image scaling: #587 
- [ ] Support for empty canvases: #577 
- [ ] Metadata (links): #571 
- [ ] JSON-LD for motivation (array vs string): #568 
- [ ] Annotations on full canvas: #567 
- [ ] Specific Resource Annotations: #551 
- [ ] non-paged viewingHint: #534 
- [ ] Ranges: #527, #94 
- [ ] Render logo (mandatory per spec): #524, #376
- [ ] Support non IIIF images: #520 
- [ ] Physical Dimensions: #493, #97 
- [ ] Text-less Annotations: #430 
- [ ] viewingDirection of non L2R: #419
- [ ] Metadata: #414 
- [ ] Image Choice: #304 
- [ ] Collections: #98 
- [ ] Canvas (rather than Manifest) Metadata: #93 
- [ ] Detail images: #632

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
